# Set to true to enable Prefect to use locally stored secrets
[cloud]
use_local_secrets = true

# Local storage for myfitnesspal user logins
[context.secrets]

# For each user to scrape this config file should have the following two lines
# with <USER> replaced by the user id that MyFitnessPaw's flow will use and 
# their username (email) and password for login in myfitnesspal.
# Example:
# MYFITNESSPAL_USERNAME_DOE = "john.doe@abc.com"
# MYFITNESSPAL_PASSWORD_DOE = "correcthorsebatterystaple"

MYFITNESSPAL_USERNAME_USER = ""
MYFITNESSPAL_PASSWORD_USER = ""

MYFITNESSPAW_SLACK_WEBHOOK_URL = ""
MYFITNESSPAW_DROPBOX_ACCESS_TOKEN = ""

[myfitnesspaw]
mfpdb_path = "database/mfp_db.sqlite"