# Set to true to enable Prefect to use locally stored secrets
[cloud]
use_local_secrets = true

# Local storage for myfitnesspal user logins
[context.secrets]

MYFITNESSPAL_USERNAME = ""
MYFITNESSPAL_PASSWORD = ""
MYFITNESSPAW_SLACK_WEBHOOK_URL = ""